// Generated by gencpp from file ROSsocket1/rtklib.msg
// DO NOT EDIT!


#ifndef ROSSOCKET1_MESSAGE_RTKLIB_H
#define ROSSOCKET1_MESSAGE_RTKLIB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/NavSatFix.h>

namespace ROSsocket1
{
template <class ContainerAllocator>
struct rtklib_
{
  typedef rtklib_<ContainerAllocator> Type;

  rtklib_()
    : header()
    , gpst(0.0)
    , state()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , delay(0.0)
    , ftest(0.0)  {
    }
  rtklib_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gpst(0.0)
    , state(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , delay(0.0)
    , ftest(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _gpst_type;
  _gpst_type gpst;

   typedef  ::sensor_msgs::NavSatFix_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _delay_type;
  _delay_type delay;

   typedef double _ftest_type;
  _ftest_type ftest;




  typedef boost::shared_ptr< ::ROSsocket1::rtklib_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROSsocket1::rtklib_<ContainerAllocator> const> ConstPtr;

}; // struct rtklib_

typedef ::ROSsocket1::rtklib_<std::allocator<void> > rtklib;

typedef boost::shared_ptr< ::ROSsocket1::rtklib > rtklibPtr;
typedef boost::shared_ptr< ::ROSsocket1::rtklib const> rtklibConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROSsocket1::rtklib_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROSsocket1::rtklib_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ROSsocket1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ROSsocket1': ['/home/doopy/Documents/sockets/socketROS/src/ROSsocket1/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ROSsocket1::rtklib_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROSsocket1::rtklib_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROSsocket1::rtklib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROSsocket1::rtklib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROSsocket1::rtklib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROSsocket1::rtklib_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROSsocket1::rtklib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09d81d6564acf16ff63a944887c5d7e9";
  }

  static const char* value(const ::ROSsocket1::rtklib_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09d81d6564acf16fULL;
  static const uint64_t static_value2 = 0xf63a944887c5d7e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROSsocket1::rtklib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROSsocket1/rtklib";
  }

  static const char* value(const ::ROSsocket1::rtklib_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROSsocket1::rtklib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 gpst\n\
sensor_msgs/NavSatFix state\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 delay\n\
float64 ftest\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/NavSatFix\n\
# Navigation Satellite fix for any Global Navigation Satellite System\n\
#\n\
# Specified using the WGS 84 reference ellipsoid\n\
\n\
# header.stamp specifies the ROS time for this measurement (the\n\
#        corresponding satellite time may be reported using the\n\
#        sensor_msgs/TimeReference message).\n\
#\n\
# header.frame_id is the frame of reference reported by the satellite\n\
#        receiver, usually the location of the antenna.  This is a\n\
#        Euclidean frame relative to the vehicle, not a reference\n\
#        ellipsoid.\n\
Header header\n\
\n\
# satellite fix status information\n\
NavSatStatus status\n\
\n\
# Latitude [degrees]. Positive is north of equator; negative is south.\n\
float64 latitude\n\
\n\
# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n\
float64 longitude\n\
\n\
# Altitude [m]. Positive is above the WGS 84 ellipsoid\n\
# (quiet NaN if no altitude is available).\n\
float64 altitude\n\
\n\
# Position covariance [m^2] defined relative to a tangential plane\n\
# through the reported position. The components are East, North, and\n\
# Up (ENU), in row-major order.\n\
#\n\
# Beware: this coordinate system exhibits singularities at the poles.\n\
\n\
float64[9] position_covariance\n\
\n\
# If the covariance of the fix is known, fill it in completely. If the\n\
# GPS receiver provides the variance of each measurement, put them\n\
# along the diagonal. If only Dilution of Precision is available,\n\
# estimate an approximate covariance from that.\n\
\n\
uint8 COVARIANCE_TYPE_UNKNOWN = 0\n\
uint8 COVARIANCE_TYPE_APPROXIMATED = 1\n\
uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2\n\
uint8 COVARIANCE_TYPE_KNOWN = 3\n\
\n\
uint8 position_covariance_type\n\
\n\
================================================================================\n\
MSG: sensor_msgs/NavSatStatus\n\
# Navigation Satellite fix status for any Global Navigation Satellite System\n\
\n\
# Whether to output an augmented fix is determined by both the fix\n\
# type and the last time differential corrections were received.  A\n\
# fix is valid when status >= STATUS_FIX.\n\
\n\
int8 STATUS_NO_FIX =  -1        # unable to fix position\n\
int8 STATUS_FIX =      0        # unaugmented fix\n\
int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation\n\
int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation\n\
\n\
int8 status\n\
\n\
# Bits defining which Global Navigation Satellite System signals were\n\
# used by the receiver.\n\
\n\
uint16 SERVICE_GPS =     1\n\
uint16 SERVICE_GLONASS = 2\n\
uint16 SERVICE_COMPASS = 4      # includes BeiDou.\n\
uint16 SERVICE_GALILEO = 8\n\
\n\
uint16 service\n\
";
  }

  static const char* value(const ::ROSsocket1::rtklib_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROSsocket1::rtklib_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gpst);
      stream.next(m.state);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.delay);
      stream.next(m.ftest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct rtklib_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROSsocket1::rtklib_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROSsocket1::rtklib_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gpst: ";
    Printer<double>::stream(s, indent + "  ", v.gpst);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::sensor_msgs::NavSatFix_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "delay: ";
    Printer<double>::stream(s, indent + "  ", v.delay);
    s << indent << "ftest: ";
    Printer<double>::stream(s, indent + "  ", v.ftest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSOCKET1_MESSAGE_RTKLIB_H
